"""inint

Revision ID: 60ed9b859f6c
Revises: 
Create Date: 2022-12-15 04:00:55.024622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ed9b859f6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=500), nullable=True),
    sa.Column('itemcost', sa.Integer(), nullable=True),
    sa.Column('itemdesc', sa.String(length=500), nullable=True),
    sa.Column('itemurl', sa.String(length=1000), nullable=True),
    sa.Column('likes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_Product_itemcost'), 'Product', ['itemcost'], unique=False)
    op.create_index(op.f('ix_Product_itemdesc'), 'Product', ['itemdesc'], unique=False)
    op.create_index(op.f('ix_Product_itemname'), 'Product', ['itemname'], unique=False)
    op.create_index(op.f('ix_Product_itemurl'), 'Product', ['itemurl'], unique=False)
    op.create_index(op.f('ix_Product_likes'), 'Product', ['likes'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_password'), 'User', ['password'], unique=False)
    op.create_index(op.f('ix_User_user'), 'User', ['user'], unique=False)
    op.create_table('user_product',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product')
    op.drop_index(op.f('ix_User_user'), table_name='User')
    op.drop_index(op.f('ix_User_password'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Product_likes'), table_name='Product')
    op.drop_index(op.f('ix_Product_itemurl'), table_name='Product')
    op.drop_index(op.f('ix_Product_itemname'), table_name='Product')
    op.drop_index(op.f('ix_Product_itemdesc'), table_name='Product')
    op.drop_index(op.f('ix_Product_itemcost'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
