"""initial migration

Revision ID: 048e9e981080
Revises: 
Create Date: 2022-10-14 13:29:01.962971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048e9e981080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assesments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('modulecode', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assesments_description'), 'assesments', ['description'], unique=False)
    op.create_index(op.f('ix_assesments_modulecode'), 'assesments', ['modulecode'], unique=True)
    op.create_index(op.f('ix_assesments_title'), 'assesments', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assesments_title'), table_name='assesments')
    op.drop_index(op.f('ix_assesments_modulecode'), table_name='assesments')
    op.drop_index(op.f('ix_assesments_description'), table_name='assesments')
    op.drop_table('assesments')
    # ### end Alembic commands ###
